package org.change.v2.model.openflow;

import org.change.v2.model.OpenFlowTable;
import org.change.v2.model.openflow.actions.AllAction;
import org.change.v2.model.openflow.actions.ApplyActionsAction;
import org.change.v2.model.openflow.actions.ClearActionsAction;
import org.change.v2.model.openflow.actions.ControllerAction;
import org.change.v2.model.openflow.actions.DecMplsTtlAction;
import org.change.v2.model.openflow.actions.DecTtlAction;
import org.change.v2.model.openflow.actions.DropAction;
import org.change.v2.model.openflow.actions.EnqueueAction;
import org.change.v2.model.openflow.actions.ExitAction;
import org.change.v2.model.openflow.actions.FinTimeoutAction;
import org.change.v2.model.openflow.actions.FloodAction;
import org.change.v2.model.openflow.actions.GotoTableAction;
import org.change.v2.model.openflow.actions.InPortAction;
import org.change.v2.model.openflow.actions.LearnAction;
import org.change.v2.model.openflow.actions.LoadAction;
import org.change.v2.model.openflow.actions.LocalAction;
import org.change.v2.model.openflow.actions.ModDlDstAction;
import org.change.v2.model.openflow.actions.ModDlSrcAction;
import org.change.v2.model.openflow.actions.ModNwDstAction;
import org.change.v2.model.openflow.actions.ModNwSrcAction;
import org.change.v2.model.openflow.actions.ModNwTosAction;
import org.change.v2.model.openflow.actions.ModTpDstAction;
import org.change.v2.model.openflow.actions.ModTpSrcAction;
import org.change.v2.model.openflow.actions.ModVlanPcpAction;
import org.change.v2.model.openflow.actions.ModVlanVidAction;
import org.change.v2.model.openflow.actions.MoveAction;
import org.change.v2.model.openflow.actions.NormalAction;
import org.change.v2.model.openflow.actions.OutputAction;
import org.change.v2.model.openflow.actions.PopAction;
import org.change.v2.model.openflow.actions.PopMplsAction;
import org.change.v2.model.openflow.actions.PopQueueAction;
import org.change.v2.model.openflow.actions.PushAction;
import org.change.v2.model.openflow.actions.PushMplsAction;
import org.change.v2.model.openflow.actions.PushVlanAction;
import org.change.v2.model.openflow.actions.ResubmitAction;
import org.change.v2.model.openflow.actions.SampleAction;
import org.change.v2.model.openflow.actions.SetFieldAction;
import org.change.v2.model.openflow.actions.SetMplsTtlAction;
import org.change.v2.model.openflow.actions.SetQueueAction;
import org.change.v2.model.openflow.actions.SetTunnel64Action;
import org.change.v2.model.openflow.actions.SetTunnelAction;
import org.change.v2.model.openflow.actions.StripVlanAction;
import org.change.v2.model.openflow.actions.WriteMetadataAction;

public interface FlowVisitor {

	void visit(FlowEntry flowEntry);
	void visit(OutputAction action);
	void visit(EnqueueAction action);
	void visit(NormalAction action); 
	void visit(FloodAction action);
	void visit(AllAction action);
	void visit(ControllerAction action);
	void visit(LocalAction action);
	void visit(InPortAction action);
	void visit(DropAction action);
	void visit(ModVlanVidAction action);
	void visit(ModVlanPcpAction action);
	void visit(StripVlanAction action);
	void visit(PushVlanAction action);
	void visit(PushMplsAction action);
	void visit(PopMplsAction action);
	void visit(ModDlSrcAction action);
	void visit(ModDlDstAction action);
	void visit(ModNwSrcAction action);
	void visit(ModNwDstAction action);
	void visit(ModTpSrcAction action);
	void visit(ModTpDstAction action);
	void visit(ModNwTosAction action);
	void visit(ResubmitAction action);
	void visit(SetTunnelAction action);
	void visit(SetTunnel64Action action);
	void visit(SetQueueAction action);
	void visit(PopQueueAction action);
	void visit(DecTtlAction action);
	void visit(SetMplsTtlAction action);
	void visit(DecMplsTtlAction action);
	void visit(MoveAction action);
	void visit(LoadAction action);
	void visit(PushAction action);
	void visit(PopAction action);
	void visit(SetFieldAction action);
	void visit(ApplyActionsAction action);
	void visit(ClearActionsAction action);
	void visit(WriteMetadataAction action);
	void visit(GotoTableAction action);
	void visit(FinTimeoutAction action);
	void visit(SampleAction action);
	void visit(LearnAction action);
	void visit(ExitAction action);
	void visit(OpenFlowTable openFlowTable);
	void visit(Match match);

}
